services:
  portfolio-website:
    image: ghcr.io/mrasterisco/mrasterisco.github.io:main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "23503:3000"

networks:
  portfolio-network:
    driver: overlay