name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 23
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: "yarn"
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn run lint
